package com.orange.hiring_automation.config;

public enum States {
    JOB_SUBMISSION, APPLICATION_SCAN, CANDIDATE_ASSESSMENT, INTERVIEW_PROCESS_STARTED, HR_INTERVIEW, TECHNICAL_INTERVIEW, PROCESS_COMPLETED
}
